Fix/group orderbook
Leasehold/lisk-dex-ui pull request #10
Opened 2020-04-20 20:47 UTC by sacOO7

- Added common group by utility
- Updated tests for the same

Note - Need to check if size is being added correctly

2020-04-20 21:35 UTC, jondubois requested changes
Minor feedback. Nice tests. Maybe the test folder can be `tests/` instead of `__tests__/`.

2020-04-20 21:35 UTC, jondubois commented on lisk-dex-electron/src/BalanceDisplay.tsx
> +import {formatThousands} from './Utils'
We should keep consistent spacing when destructuring objects.
Either change this to:

```
import { formatThousands } from './Utils'
```

Or remove the spaces everywhere else.

2020-04-20 21:35 UTC, jondubois commented on lisk-dex-electron/src/Orderbook.js
> +import {groupByKey, Values} from './Utils'
Inconsistent spacing here. Also check other parts of the code too.

2020-04-20 21:35 UTC, jondubois commented on lisk-dex-electron/src/Orderbook.js
> +      const groupedAskOrders = Values(groupByKey(this.props.orderBookData.asks, "price", "sizeRemaining"))
We should use consistent style for strings. Currently, it's single quote `'` for logic and double quotes `"` only for HTML attributes.

2020-04-20 21:35 UTC, jondubois commented on lisk-dex-electron/src/__tests__/Utils.test.js
> +describe("Utils tests => ", () => {
The current convention is single quotes for strings `'`.

2020-04-20 21:35 UTC, jondubois commented on lisk-dex-electron/src/__tests__/Utils.test.js
> +    const expectedKeys = ["0.8", "0.85", "0.86", "0.9", "0.92"]
Missing semicolon at the end of this line. Also line 29 above and other places.

2020-04-21 04:57 UTC, sacOO7 commented
> Minor feedback. Nice tests. Maybe the test folder can be `tests/` instead of `__tests__/`.

Yes, I was going through jest documentation. It suggested to use folder name to be __tests__ that way you don't have to append .test to each js file.

2020-04-21 04:58 UTC, sacOO7 commented
Haha, I will do the remaining changes, I guess having webstorm will be a good idea probably... I don't know why it didn't give me linting error while building the code on the local.

2020-04-21 20:01 UTC, jondubois approved these changes

2020-04-21 20:01 UTC, jondubois commented on lisk-dex-electron/src/Utils.js
> +const Values = (dict) => Object.values(dict)
No big deal but I think these two wrappers `Values` and `Keys` are not necessary, it's OK to use `Object.values()` and `Object.keys()` in many parts of the code. It's not much to type out and saved having to import one more util.

2020-04-21 20:02 UTC, merged